//=== MENU ===
export const GET_MENU = 'GET_MENU';
export const SET_MENU = 'SET_MENU';
export const MENU_REQUEST_FAILED = 'MENU_REQUEST_FAILED';


//=== ORDER ITEM ===
export const ADD_TO_ORDER = 'ADD_TO_ORDER';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

//=== ORDER ===
export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const DISCARD_ORDER = 'DISCARD_ORDER';
export const ORDER_REQUEST_FAILED = 'ORDER_REQUEST_FAILED';
export const SET_ORDER_ID = 'SET_ORDER_ID';


//==== FACILITY ===
export const SET_FACILITY_INFO = 'SET_FACILITY_INFO';